### ISSUE TITLE
HUGE ISSUE

### ISSUE THREAD

**Issue by miskamero** [jooapa/KlinoffVault#1]
Klinoff OS will drop tonight. KlinoffVault will be brutally taken down. KlinoffVault will be down. KlinoffVault will be vaulted over.

-Nöfnöf
![klinf](https://github.com/jooapa/KlinoffVault/assets/114387213/3e09b691-daec-4ad0-90ef-372b10b0b4cb)

**Comment by miskamero** [comment]
API KEYS FOR KLINOFFVAULT LEAKED

⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢉⢤⣢⡢⣉⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⠿⢋⢋⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⢡⡫⡣⡢⢫⢺⡂⣹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⠃⣜⢮⢳⠹⣕⠜⣿⡿⠿⠟⢛⢛⠛⡂⢯⣪⡸⡸⠕⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣷⡈⢮⡣⡱⡱⡸⣕⢤⡲⡺⣪⡳⡳⣝⢮⡳⡵⣝⢮⡢⣌⢍⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣷⡄⠉⣚⢮⡺⣪⡳⣝⣝⢮⢎⢯⣪⡳⣝⢞⢼⢕⣝⢮⡳⣝⢖⢤⡉⠻⢿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡿⠋⣠⡺⣪⡳⣝⢮⡺⡪⡮⡳⣝⢵⢕⣝⢮⡫⡮⡳⣕⢗⣝⢮⣫⢳⢝⢵⢄⠙⢿⣿⣿⣿⣿⣿
⣿⣿⣿⠟⢁⡜⡮⣺⡪⣺⡪⡳⣝⢵⢝⢞⢮⡳⣣⡳⡳⣝⢮⡫⡮⡳⣕⢗⢵⢝⢵⢝⢕⣗⢄⠙⣿⣿⣿⣿
⣿⣿⠏⠀⡅⣆⢥⡳⣝⢮⢎⢯⣪⡳⣝⡕⣗⢝⢮⢎⢯⣪⡳⣝⢮⡫⡮⡫⡮⡫⡮⣔⢔⢌⢗⢥⠈⢻⣿⣿
⣿⠇⢠⢯⡺⣪⡳⣝⢮⡳⣝⢵⢕⢝⢎⣎⣎⢭⢕⣍⣇⢳⢹⢪⡳⣝⢮⡫⡮⣫⡺⡪⡯⣪⣫⡳⣕⠄⢻⣿
⡏⢀⡗⣕⣭⣮⣼⣸⠱⣝⠮⡣⣣⣳⣳⡳⡳⣝⣗⣗⢽⣕⢷⢕⢝⠼⣕⣝⢞⢜⣼⣼⣮⣎⡎⣞⢮⡣⠀⢿
⠁⢰⣱⣿⣿⣿⣿⣿⣷⢕⢵⢝⣞⣞⢞⢮⣻⣺⣺⣪⡳⡽⣝⣝⢷⢕⢕⢕⣵⣿⣿⣿⣿⣿⣿⡎⡧⣫⡃⠸
⠂⢱⣿⣿⠁⠉⣿⣿⡟⣕⣝⣗⢗⠁⠄⡑⣗⣗⣕⠇⡉⢉⠺⡪⡯⣯⢪⢱⣿⣿⣿⣿⡇⠀⣸⣿⢸⡪⣎⠀
⠀⢊⢿⣿⣷⣿⣿⣿⡇⣞⢞⢮⢇⠠⠁⡀⣗⣕⣗⠅⠐⡀⠂⡯⡯⡮⡇⡣⡻⣿⣿⣿⣿⣿⣿⢏⢪⡺⡜⠀
⡇⠨⡪⡹⠻⠿⠿⡻⡱⡸⡽⣝⣗⣄⣅⣔⣗⣗⣗⣗⢥⢤⢯⡫⡯⡯⡪⡺⣜⢌⢻⠻⡻⡫⡱⡸⣕⡝⡎⢠
⣧⠀⢣⢫⣹⡸⣱⡱⡵⣕⢝⢞⣞⢞⣞⢮⡺⣮⣺⡪⡯⡯⡳⡽⡽⡱⣕⣝⢮⡳⡵⡱⣕⢵⢝⢞⢮⡪⠀⣼
⣿⣧⡀⠣⡳⣝⢮⡺⡪⡮⡳⣕⢕⡓⡗⡗⡝⡞⡮⠯⡫⡫⡫⡹⣜⢞⣜⢮⡳⣝⢮⡫⡮⡳⣝⢕⠳⠀⣼⣿
⣿⣿⣷⣄⠈⠎⡗⡽⣕⣝⢞⢮⡳⡵⣱⢱⡱⡱⡪⡣⡳⡱⣝⢞⢮⡳⣕⢗⣝⢮⡳⣝⢮⡫⡪⠃⣠⣾⣿⣿
⣿⣿⣿⣿⣷⣄⠈⠊⢎⢎⢯⢳⢝⢞⢮⡳⣝⢞⢮⡫⡮⡫⡮⣫⡺⡪⡮⡳⣕⢗⢝⠎⠎⠈⣠⣶⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣦⣄⡈⠘⠘⠕⢍⢗⢝⢎⢯⢚⢎⢯⢪⢫⢪⢪⢫⠪⠪⠊⠊⣀⣤⣶⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⣤⣠⣀⣁⣈⢈⢈⢈⢈⣀⣁⣠⣠⣤⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

                                                                                
                                                                                


                                                                                
                                                                                
                            ,/((///////////////////((/.                         
                     ,(/////////////////##########(/////////                    
                 (///////////////////######@@@@@@@@@@##(//////(                 
              (//////////////////////#####%@@@@@@@@@@@###////////(              
           ./////////////////////////########@@@@@@@%####(//////////            
          *////////////////////////////#################(////////////           
        ,**///////////////////////////////(##########(////////////////.         
       ,***////////////////////////////////////////////////////////////         
       ****////////////////////////////////////////////////////////////(        
      /*****////////////////////////////////////////////////////////////*       
      *********/....////////////////////////////////////....,//////*****/       
      *************//////////////////////////////////////****************       
      /************************,*/(((((/*,,******************************       
      ,*******,%@@@@&,*/**,,/((((((((((((((((/**/*****,@@@@@@&,**********       
       *****,@@@@@@@@@@(/,/(((((((((((((((((((((,(((.@@@@@@@@@@@,*******/       
        ,/ ,@@*  @@@@@@@,((((( ..,(((((/  .((((((,(,@@@@@@@.  @@# .*****        
        ,,.,@@@#@@@@@@@(*(((( ....((((/.... (((((,(/#@@@@@@@@@@@,/((            
       *,,, ,&@@@@@@@@@,,((((/... (((((,.../(((((,((*.@@@@@@@@@,*((/ ,,*/       
      /,,,. /**,,//,,**/,/((((((((((((((((((((((,/((((***,,,***/(((( *,,,//     
   /,,* ,,   *((/**/((((((,/((((((((((((((((((**(((((((((((((((((((*  ,,,,/(%   
  /,, *,,,    //((((((((((((//,,,**////*,,,//((((((((((((((((((((*     .(*( (#. 
  /*,,,,,       (/(((((((((((((///////////(((((((((((((((((((((/        (/(%    
                   ///(((((((((((((((((((((((((((((((((((((/*,                  
                      ,////((((((((((((((((((((((((((////*                      
                            ,/////*////////////////.

**Comment by jooapa** [comment]
![Kingcry](https://github.com/jooapa/KlinoffVault/assets/37744313/3b5f97a5-c0c5-4c21-acfe-97cc7a9ba30f)

**Comment by miskamero** [comment]
°⁠ ͜⁠°

**Comment by miskamero** [comment]
![klinoffrecord](https://github.com/jooapa/KlinoffVault/assets/114387213/61986b5e-44ed-44a8-b799-73ac38d0dddd)
FILMING THE DESTRUCTION OF KLINOFFVAULT TM

**Comment by miskamero** [comment]
![lataus](https://github.com/jooapa/KlinoffVault/assets/114387213/a57a5563-1cf6-42db-9bc7-6822a94e05e8)

**Comment by miskamero** [comment]
![badklinoff](https://github.com/jooapa/KlinoffVault/assets/114387213/8ead6730-bc6b-4512-adae-666e788223d0)
PIGGY MACHINE, NOT FIT FOR KLINOFFVAULT

**Comment by miskamero** [comment]
![hihiklinoff](https://github.com/jooapa/KlinoffVault/assets/114387213/7505833d-4d3a-47be-8f6f-bf52e16967b3)
# KLINOFF

**Comment by miskamero** [comment]
![participating](https://github.com/jooapa/KlinoffVault/assets/114387213/dca9de66-11ec-4b73-b7a3-ed29efa7c686)
_**PARTICIPATING IN THE DESTRUCTION**_

**Comment by jooapa** [comment]
Klinoff-os will be taken down by my klinoff-lawyers
![Faraway](https://github.com/jooapa/KlinoffVault/assets/37744313/2046e5d4-80bf-4a6b-9595-0a5c83ad5ab2)

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/75fdffb7-1989-49d2-9cf1-4ca29a4d1538)
KLINOFF DEFENCE

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/3aa0f1b6-15c9-4683-afe0-7f331e361b57)
KING PIG LAWYERS **huooownah**

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/544930ce-ea99-4873-9fa1-78bfd212949c)
SPYING ON KLINOFFVAULT. SECRETS REVEALED, CODE _**CRACKED**_

**Comment by jooapa** [comment]
![AngryBirdsStarWars2Cover](https://github.com/jooapa/KlinoffVault/assets/37744313/9f903692-8903-4ff5-a6a1-929d7bbe915d)
Me getting the latest details on klinoff-os **ominous laughing in the darkness**

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/4dd23304-72a8-4d00-a62d-7f2008f6a1db)
Army to brutally take down  Klinoff"Vault"

**Comment by jooapa** [comment]
no please dont
![756mge](https://github.com/jooapa/KlinoffVault/assets/37744313/2bfab7f0-a824-4cb5-aa0d-424952ef53e0)

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/014e08a4-e6e0-439e-a950-236325bb5fe7)
PiggyLand, With klinoff OS

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/3b13f42d-25a5-44a6-bc2b-c49da0b12e97)
PiggyLand with klinoffvault

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/01776b64-5dde-45b6-9722-da6fae115062)


Filming potential takedown of KlinoffVault

**Comment by jooapa** [comment]
![x1080](https://github.com/jooapa/KlinoffVault/assets/37744313/618b77fb-fae1-44ab-bac2-e461fb2c9eba)
KlinoffVaults employeers watching klinoff-os crumble down

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/f44d48bd-4598-42b8-b2b4-97c10b68e61a)
Average citizen when hearing about "KlinoffVault"

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/645429ef-f3e8-4c5b-8b2e-7beca321ad88)
Watching the disaster of Klinoff"Vault"

**Comment by jooapa** [comment]
most cleanest house inside klinoff-os metropolis
![445150525-56ff29117ffcb33d2725ee86d7293b6077d77b47f8eb4e2f160b53e6d93070b1-d_750x421](https://github.com/jooapa/KlinoffVault/assets/37744313/4851be72-4448-471e-8865-b0fb7d9f9990)

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/740eaad0-8b5f-4344-a7ae-08a5a237717b)

Better King Pig representing Klinoff OS

**Comment by jooapa** [comment]
KlinoffVault taking a huge dump on klinoff-os
![FBvk0ZGWQBs9KIV](https://github.com/jooapa/KlinoffVault/assets/37744313/e82ea10f-d097-47a9-a8d2-e0f521409a87)

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/23f18d13-65a4-45f5-b65a-12e4be8b33a4)

Klinoff marriage, happy end

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/8ab10e9f-0a8e-4b5c-ae5d-514780f4a5ed)

Klinoff"Vault" after Klinoff OS encounter

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/5915a2d4-9587-4d8b-bb54-5a51c66f047b)
Imagery of revenue from Klinoff OS, all going to charity

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/631d50a8-d81a-440f-932b-e6bad5aa68ae)
Riding the high after destruction of Klinoff"Vault"

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/305ca3af-45d0-4b81-ad71-d918190245bc)
King Pig Opinion of Klinoff"Vault"

**Comment by jooapa** [comment]
I am a klinoff sexual 
![EvpjIC6WYAoPbhh](https://github.com/jooapa/KlinoffVault/assets/37744313/b0431767-91d5-4327-8ff8-bd9ac697d992)

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/74134f4d-57a2-4f14-8f90-e90bb5a36f7d)
Leader of Klinoff"Vault"

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/ae7c1e8a-0175-49f7-ae6e-7b31d6d8c041)
Klinoff kopla

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/d3c3ff87-933f-4510-bbfc-c9995d5ef0b2)
Dataminers, used to destroy and mine Klinoff"Vault"

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/e84df0f6-d5b9-4959-84b2-e98be5492c8e)
Klinoff"Vault" after seeing Klinoff OS

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/ca1d96f2-79bf-47ad-b6d2-2992d0481b4d)
Klinoff bomb from Klinoff OS

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/fbce8a86-be8f-4db8-96c4-73da7a3e12a1)
Mocking stupidity of Klinoff"Vault"

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/56f12faf-26ed-443f-bab7-31738403e05c)
Klinoff"Vault" Drowning from takedowns

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/6f23b955-e75d-449e-bb25-e2a4b597685b)
Klinoff"Vault" only defense

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/f23a6cee-752c-4756-96e0-54b912c04f9d)
Klinoff"Vault" Fearing Klinoff OS raw POWER

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/04e454d5-a3ef-4359-be10-5551724c85b1)
Fear of Klinoff"Vault"

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/ebb0deb1-414d-4e76-8a26-70bc568f6ecf)
Klinoff"Vault" pokey

**Comment by jooapa** [comment]
Stop this right now 
![Nimetön](https://github.com/jooapa/KlinoffVault/assets/37744313/45ff5f6d-df7c-46b2-bc99-cfda5fe0be57)

**Comment by miskamero** [comment]
![image](https://github.com/jooapa/KlinoffVault/assets/114387213/fcc7cedc-3eed-4615-8eeb-30d242ea80d7)
We will see in court.
